v1.4.3

diff --git a/bin/fz b/bin/fz
--- a/bin/fz
+++ b/bin/fz
@@ -5,18 +5,23 @@ set -o nounset
 set -o pipefail
 
 readonly APP_NAME="${0##*/}"
-readonly VERSION="1.4.2"
+readonly VERSION="1.4.3"
+
+readonly COLOR_CYAN=$'\033[1;36m'
+readonly COLOR_MAGENTA=$'\033[35m'
+readonly COLOR_DIM=$'\033[2m'
+readonly COLOR_RESET=$'\033[0m'
 
 function fz::env()
 {
 	local var=""
 
 	var=$( env | sort | awk -F= '{ value = substr( $0, length( $1 ) + 2 ) ; gsub( /\033/, "\\E", value ) ; printf "\033[1;36m%s\033[0m\033[35m=\033[0m%s\n", $1, value }' \
-		| fzf --ansi --prompt="env > " --reverse --select-1 \
+		| __fz::fzf --ansi --prompt="env > " --reverse --select-1 \
 		| cut -d= -f1 \
 	)
 
-	printf "\033[1;36m%s\033[0m\033[35m=\033[0m\033[2m%q\033[0m\n" "${var}" "${!var}"
+	[[ -z "${var}" ]] || printf "${COLOR_CYAN}%s${COLOR_MAGENTA}=${COLOR_RESET}${COLOR_DIM}%q${COLOR_RESET}\n" "${var}" "${!var}"
 }
 
 function fz::kill()
@@ -37,24 +42,25 @@ function fz::kill()
 		local returnCode=0
 
 		msg=$( builtin kill "${signal}" "${pid}" 2>&1 ) || {
-			returnCode="${?}"
-			printf "kill: %s\n" "${msg#*: kill: }" >&2
+			returnCode=$?
+			printf 'kill: %s\n' "${msg#*: kill: }" >&2
 		}
 
-		return "${returnCode}"
+		return ${returnCode}
 	}
 
 	local signal="${1:--SIGTERM}"
-	local procs=""
 	local selection=""
 	local key=""
 	local pid=""
 
-	__fz::kill::isSignal "${signal}" || return "${?}"
-	[[ "${signal}" == -* ]] || signal="-${signal}"  # make it -SIGNAL
+	__fz::kill::isSignal "${signal}" || return $?
+	signal="${signal^^}"                            # uppercase
+	[[ "${signal}" == -* ]] || signal="-${signal}"  # make it "-SIGNAL"
 
-	procs=$( ps aux )
-	selection=$( fzf --exact --expect="enter,ctrl-k" --header=$'\n[ Enter ] ..... kill '"${signal}"$'\n[ Ctrl + k ] .. force -SIGKILL\n\n' --header-lines=1 --prompt="kill ${signal} > " --select-1 --tac <<< "${procs}" )
+	selection=$( ps aux \
+		| __fz::fzf --exact --expect="enter,ctrl-k" --header=$'\n[ Enter ] ..... kill '"${signal}"$'\n[ Ctrl + k ] .. force -SIGKILL\n\n' --header-lines=1 --prompt="kill ${signal} > " --select-1 --tac
+	)
 
 	key=${selection%%$'\n'*}                        # fzf --expect outputs the key pressed on the first line
 	selection=${selection#*$'\n'}                   # remove the key line, leaving the selected process
@@ -64,9 +70,12 @@ function fz::kill()
 		enter) ;;
 
 		ctrl-k)
-			__fz::confirm $'kill -SIGKILL ( \033[1;36m'"${selection}"$'\033[0m )\n\nAre you sure?' || return 0
+			__fz::confirm "Kill ?\n\n\tSIGKILL ( ${COLOR_CYAN}${selection}${COLOR_RESET} )" || return 0
 			signal="-SIGKILL"
 		;;
+
+		"")
+			return 0 ;;                             # fzf cancelled
 	esac
 
 	__fz::kill::kill "${signal}" "${pid}"
@@ -80,28 +89,29 @@ function fz::man()
 
 	binBatcat=$( command -v batcat || command -v bat )
 
-	[[ -n "${binBatcat}" ]] && \
-		fzfPreview+=' | bash -c "col -bx | '"${binBatcat}"' --color=always --language=man --paging=never --style=plain"'
+	[[ -n "${binBatcat}" ]] && fzfPreview+=' | bash -c "col -bx | '"${binBatcat}"' --color=always --language=man --paging=never --style=plain"'
 
 	man -k . 2>/dev/null \
-		| fzf --preview="${fzfPreview}" --preview-window="right:70%" --prompt="man > " --query="^${*}" --reverse --select-1 \
+		| __fz::fzf --preview="${fzfPreview}" --preview-window="right:70%" --prompt="man > " --query="^$*" --reverse --select-1 \
 		| awk '{ gsub( /[ (),]/, " " ) ; print $2, $1 }' \
-		| xargs -I {} printf "man %s\n" {} \
+		| xargs -I {} printf 'man %s\n' {} \
 		| bash
 }
 
 function fz::ssh()
 {
+	export -f __fz::fzf
+
 	local fzfPreview="ssh -G -T {} 2>/dev/null | grep -E '^(host|user|hostname|port|identityfile)[[:space:]]' | column -t"
 	local sshServer=""
 
 	sshServer=$( bash --noprofile --norc -ic '
-		source <( fzf --bash )
-		__fzf_list_hosts | fzf --height="30%" --preview="'"${fzfPreview}"'" --prompt="ssh > " --reverse --select-1
+		source <( __fz::fzf --bash )
+		__fzf_list_hosts | __fz::fzf --height="30%" --preview="'"${fzfPreview}"'" --prompt="ssh > " --reverse --select-1
 	' )
 
 	# shellcheck disable=SC2029                     # SC2029: Note that, unescaped, this expands on the client side.
-	ssh "${@}" "${sshServer}"
+	[[ -z "${sshServer}" ]] || ssh "${@}" "${sshServer}"
 }
 
 command -v tmux &>/dev/null && function fz::tmux()
@@ -117,7 +127,7 @@ command -v tmux &>/dev/null && function fz::tmux()
 			tmux list-panes -a -F "pane #S:#I.#P #{pane_current_command}"
 		} \
 		| column -t \
-		| fzf --expect="enter,ctrl-k" --header=$'\n[ Enter ] ..... attach / switch\n[ Ctrl + k ] .. kill\n\n' --prompt="tmux > " --reverse --select-1 --tmux \
+		| __fz::fzf --expect="enter,ctrl-k" --header=$'\n[ Enter ] ..... attach / switch\n[ Ctrl + k ] .. kill\n\n' --prompt="tmux > " --reverse --select-1 --tmux
 	)
 
 	key=${selection%%$'\n'*}                        # fzf --expect outputs the key pressed on the first line
@@ -136,7 +146,12 @@ command -v tmux &>/dev/null && function fz::tmux()
 			if [[ -n "${TMUX}" ]] ; then tmux select-window -t "${selectedTarget}" \; select-pane -t "${selectedTarget}" ; else tmux attach -t "${selectedTarget%%:*}" \; select-pane -t "${selectedTarget}" ; fi ;;
 
 		ctrl-k:session|ctrl-k:window|ctrl-k:pane)
-			tmux kill-"${selectedType}" -t "${selectedTarget}" ;;
+			__fz::confirm "Kill ?\n\n\tTMUX ${COLOR_CYAN}${selectedType}${COLOR_RESET} ( ${COLOR_CYAN}${selectedTarget}${COLOR_RESET} )" || return 0
+			tmux kill-"${selectedType}" -t "${selectedTarget}"
+		;;
+
+		:)
+			return 0 ;;                             # fzf cancelled
 	esac
 }
 
@@ -193,12 +208,14 @@ function __fz::confirm()
 	local msg="${1:-"Proceed?"}"
 	local answer=""
 
-	answer=$( printf "%s\n" "Yes" "No" | fzf --header="${msg}"$'\n\n' --height=8 --no-info --no-input --prompt="${FUNCNAME[1]} > " --reverse --border=rounded)
+	printf -v msg '%b\n\n' "${msg}"
+
+	answer=$( printf '%s\n' 'Yes' 'No' | __fz::fzf --border=rounded --disabled --header="${msg}" --height=10 --no-info --prompt="${FUNCNAME[1]} > " --reverse )
 	[[ "${answer}" == "Yes" ]]
 }
 
 # treat fzf cancellation (130) as success to avoid triggering pipefail
-# function __fz::fzf() { fzf "$@" || [[ "${?}" == 130 ]] ; }
+function __fz::fzf() { fzf "$@" || (( $? == 130 )) ; }
 
 function __fz::help()
 {
@@ -228,43 +245,36 @@ function __fz::main()
 
 	case "${arg}" in
 		--bash-completion)
-			__fz::completion::bash
-			return 0
-		;;
+			__fz::completion::bash ;;
 
 		--zsh-completion)
-			__fz::completion::zsh
-			return 0
-		;;
+			__fz::completion::zsh ;;
 
 		-h|--help)
-			__fz::help
-			return 0
-		;;
+			__fz::help ;;
 
 		-V|--version)
-			__fz::version
-			return 0
-		;;
+			__fz::version ;;
 
 		*)
 			command -v fzf &>/dev/null || {
-				printf "%s\n" "[${APP_NAME} error]: Install \"fzf\" to use ${APP_NAME}."
+				printf '%s\n' "[${APP_NAME} error]: Install \"fzf\" to use ${APP_NAME}."
 				return 1
 			}
 
 			declare -F "fz::${arg}" &>/dev/null || {
-				printf "%s\n" "[${APP_NAME} error]: Found argument \"${arg}\" which wasn't expected. Try --help."
+				printf '%s\n' "[${APP_NAME} error]: Found argument \"${arg}\" which wasn't expected. Try --help."
 				return 1
 			}
 
 			shift
-			fz::"${arg}" "${@}"
-			return "${?}"
+			fz::"${arg}" "$@"
 		;;
 	esac
+
+	return $?
 }
 
-function __fz::version() { printf "%s\n" "${APP_NAME} ${VERSION}" ; }
+function __fz::version() { printf '%s\n' "${APP_NAME} ${VERSION}" ; }
 
-__fz::main "${@}"
+__fz::main "$@"
